config/routes.rb
ElvoWarehouse::Application.routes.draw do
  devise_for :users

  root :to => 'storages#index'

  resources :halls do
    resources :locations
  end

  resources :storages

  resources :pending_placements, only: :index

  resources :stock_articles, only: [:index, :show] do
    resources :placements, except: [:index, :show]
  end

end

app/models/cell.rb
class Cell < ActiveRecord::Base
  belongs_to :hall
  belongs_to :location
end

app/models/hall.rb
class Hall < ActiveRecord::Base
  belongs_to :storage
  belongs_to :user
  has_many :locations, dependent: :destroy
  has_many :cells, dependent: :destroy

  after_create :create_cells


  private

  def create_cells
    for y in 1..self.length
      for x in 1..self.width
        cells.create!(
            coordinate_x: x,
            coordinate_y: y
        )
      end
    end
  end
end

app/models/location.rb
# TODO Vyresit min a max souradnice výběru
class Location < ActiveRecord::Base
  belongs_to :hall
  has_many :cells, dependent: :nullify
  has_many :placements, dependent: :destroy
  has_many :stock_articles, through: :placements

  enum location_type: [:ground, :rack]

  after_create :assign_cells
  before_create :compute_capacity


  protected

  def assign_cells
    Cell.where(
        "coordinate_x >= ? AND coordinate_y >= ? AND coordinate_x <= ? AND coordinate_y <= ?",
        selection_start_x,
        selection_start_y,
        selection_end_x,
        selection_end_y
    ).update_all(location_id: self.id)
  end

  def compute_capacity
    self.capacity = default_cell_capacity * (selection_end_x - selection_start_x + 1) * (selection_end_y - selection_start_y + 1)
  end

  def default_cell_capacity
    case location_type
      when 'ground' then 2
      else nil
    end
  end

end

app/models/placement.rb
class Placement < ActiveRecord::Base
  belongs_to :location
  belongs_to :stock_article

  # TODO Přidat validace
end

app/models/stock_article.rb
class StockArticle < ActiveRecord::Base
  has_many :placements, dependent: :destroy
  has_many :locations, through: :placements

  def quantity_placed
    placements.sum(:quantity)
  end
end

app/models/storage.rb
class Storage < ActiveRecord::Base
  has_many :halls, dependent: :destroy
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :storages
  has_many :halls
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :authenticate_user!
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/halls_controller.rb
class HallsController < ApplicationController
  def index
    @halls = Hall.all
  end

  def new
    @hall = Hall.new
    @storages = Storage.all
  end

  def create
    @halls = Hall.new(app_params)
    if @halls.save
      redirect_to halls_path, notice: 'Hall was created'
    end
  end

  def show
    @hall = Hall.find(params[:id])
    @location = @hall.locations.new
    @locations = @hall.locations.all
  end

  def edit
    @hall = Hall.find(params[:id])
    @storages = Storage.all
  end

  def update
    @hall = Hall.find(params[:id])

    if @hall.update_attributes(app_params)
      redirect_to halls_path
    end
  end

  def destroy
    @hall = Hall.find(params[:id])
    if @hall.destroy
      redirect_to halls_path
    end
  end

  private
  def app_params
    params.require(:hall).permit(:id, :name, :storage_id, :updated_at, :created_at, :width, :length)
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def new

  end

  def create
    @hall = Hall.find(params[:hall_id])
    @location = @hall.locations.new(location_params)
    if @location.save
      redirect_to hall_url(@hall), notice: 'Location created'
    else
      render 'halls/show'
    end
  end

  def destroy
    @location = Location.find(params[:id])
    if @location.destroy
      redirect_to halls_path, notice: 'Location destroyed'
    end
  end

  private
  def location_params
    params.require(:location).permit(:id, :name, :selection_start_x, :selection_start_y, :selection_end_x, :selection_end_y, :location_type)
  end
end

app/controllers/pending_placements_controller.rb
class PendingPlacementsController < ApplicationController
  def index
    @stock_articles = StockArticle.
        where('stock_articles.quantity > 0').
        includes(:placements).
        references(:placements).
        select('stock_articles.*').
        group('placements.id, stock_articles.id').
        having('SUM(placements.quantity) < stock_articles.quantity OR placements.id IS NULL').
        paginate(page: params[:page], per_page: 25)
  end
end

app/controllers/placements_controller.rb
class PlacementsController < ApplicationController
  def new
    @stock_article = StockArticle.find(params[:stock_article_id])
    @placement = @stock_article.placements.new
  end

  def create
    @stock_article = StockArticle.find(params[:stock_article_id])
    @placement = @stock_article.placements.new(placement_params)
    if @placement.save
      redirect_to pending_placements_url, notice: 'Placement created'
    else
      redirect_to pending_placements_url, notice: 'Placement creation failed'
      # raise?
    end
  end

  def update

  end


  protected

  def placement_params
    params.require(:placement).permit(:location_id, :stock_article_id, :quantity)
  end
end

app/controllers/storages_controller.rb
class StoragesController < ApplicationController
  def index
    @storages = Storage.all
  end

  def new
    @storage = Storage.new
  end

  def create
    @storage = Storage.new(app_params) # Tady se musi pouzit params.require (viz app_params) - attr_accessible nefunguje
    if @storage.save
      redirect_to storages_path, notice: 'Storage created'
    else
      redirect_to new_storage_path, notice: 'Not created'
    end
  end

  def destroy
    @storage = Storage.find(params[:id])
    @storage.destroy
    redirect_to storages_path
  end

  def show
    @storage = Storage.find(params[:id])
  end

  def edit
    @storage = Storage.find(params[:id])
  end

  def update
    @storage = Storage.find(params[:id])

    if @storage.update_attributes(app_params)
      redirect_to storages_path
    end
  end

  private
  def app_params
    params.require(:storage).permit(:id, :name, :updated_at, :created_at)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cell_helper.rb
module CellHelper
end

app/helpers/cells_helper.rb
module CellsHelper
end

app/helpers/halls_helper.rb
module HallsHelper
end

app/helpers/location_helper.rb
module LocationHelper
end

app/helpers/storages_helper.rb
module StoragesHelper
end

app/views/halls/_form.html.erb
<%= form_for @hall do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %><br>

    <%= f.label 'Select storage' %>
    <%= f.collection_select :storage_id, @storages, :id, :name %>
    <br>

    <%= f.label :width %>
    <%= f.number_field :width %>
    <br>

    <%= f.label :length %>
    <%= f.number_field :length %>
    <br>

    <%= f.submit :save %>
<% end %>

app/views/halls/edit.html.erb
<h1>Edit hall "<%= @hall.name %>"</h1>
<%= render 'form' %>

app/views/halls/index.html.erb
<h1>My halls</h1>
<table>
  <tr>
    <th>Hall name</th>
    <th>Belongs to storage</th>
    <th>Size</th>
  </tr>

  <% @halls.each do |hall| %>
    <tr>
    <td><%= link_to hall.name, hall_path(hall) %></td>
    <td><%= link_to hall.storage.name, storage_path(hall.storage.id) %></td>
    <td><%= hall.width || 0 %> x <%= hall.length || 0 %></td>
    <td><%= link_to 'Edit', edit_hall_path(hall) %></td>
    <td><%= link_to 'Destroy', hall, method: :delete, data: { confirm: 'Sure?' } %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'Create a new hall', new_hall_path %>

app/views/halls/new.html.erb
<h1>Create a hall</h1>
<%= render 'form' %>

app/views/halls/show.html.haml
:css
  table, td { border: 1px solid black;}
  td { width: 80px; height: 80px; }

%h1 Hall "#{@hall.name}"
%p Belongs to storage #{link_to @hall.storage.name, storage_path(@hall.storage.id)}.
%table
  - for y in 1..@hall.length
    %tr
      - for x in 1..@hall.width
        %td
          [x: #{x}, y: #{y}]
          #{@hall.cells.where(coordinate_x: x, coordinate_y: y).last.location.try(:name)}

= link_to 'Edit', edit_hall_path(@hall)

%h2 Locations
%table
  %tr
    %th Name
    %th Start point
    %th End point
    %th Capacity

  - @locations.each do |location|
    %tr
      %td #{location.name}
      %td x: #{location.selection_start_x}, y: #{location.selection_start_y}
      %td x:#{location.selection_end_x}, y: #{location.selection_end_y}
      %td= location.capacity
      %td
        =link_to 'Destroy', hall_location_path(@hall, location), method: :delete, data: { confirm: 'Sure?' }

%h2 Create a new location
= form_for([@hall, @location]) do |f|
  = f.label :name
  = f.text_field :name
  %br

  = f.label :location_type
  = f.collection_radio_buttons :location_type, Location::LOCATION_TYPE, :first, :first
  %br

  = f.label :selection_start
  = f.text_field :selection_start_x
  = f.text_field :selection_start_y
  %br

  = f.label :selection_end
  = f.text_field :selection_end_x
  = f.text_field :selection_end_y

  %br

  = f.submit

  %br

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ElvoWarehouse</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="user_nav">
  <% if user_signed_in? %>
    Signed in as <%= current_user.email %>. <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
  <% end %>
</div>

<%= yield %>

<% if current_user %>
<ul>
  <li><%= link_to 'Storages', storages_path %></li>
  <li><%= link_to 'Halls', halls_path %></li>
</ul>

<% end %>
</body>
</html>

app/views/locations/index.html.erb
<h1>Location#index</h1>
<p>Find me in app/views/location/index.html.erb</p>

app/views/locations/new.html.erb
<h1>Location#new</h1>
<p>Find me in app/views/location/new.html.erb</p>

app/views/pending_placements/index.html.haml
%h1 Pending placements
= will_paginate @stock_articles
%table
  %tr
    %th Cezar ID
    %th Name
    %th Quantity
    %th Already placed

  - @stock_articles.each do |article|
    %tr
      %td
        = article.cezar_id
      %td
        = article.name

      %td
        = article.quantity

      %td
        = article.quantity_placed
        
      %td
        = link_to 'Create placement', new_stock_article_placement_path(article)

= will_paginate @stock_articles

app/views/placements/_form.html.haml
= form_for([@stock_article, @placement]) do |f|
  = f.label :location_id
  = f.collection_select :location_id, Location.all, :id, :name
  %br

  = f.label :quantity
  = f.number_field :quantity
  %br

  = f.submit

app/views/placements/new.html.haml
%h1 Create placement
=render 'form'

app/views/storages/_form.html.erb
<%= form_for(@storage) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.submit 'Rename' %>
<% end %>

app/views/storages/edit.html.erb
<h1>Rename "<%= @storage.name %>"</h1>
<%= render 'form' %>

app/views/storages/index.html.erb
<h1>My storages managment</h1>
<table>
  <tr><th>Name</th></tr>
<% @storages.each do |storage| %>
  <tr>
    <td><%= link_to storage.name, storage_path(storage)%> (halls: <%= storage.halls.count %>)</td>
    <td><%= link_to 'Rename', edit_storage_path(storage) %></td>
    <td><%= link_to 'Delete', storage, method: :delete, data: { confirm: 'Sure?' } %></td>
  </tr>
<% end %>
</table>
<%= link_to 'Add a new storage', new_storage_path %>

app/views/storages/new.html.erb
<h1>Add a new storage</h1>
<%= render 'form' %>

app/views/storages/show.html.erb
<h1>Storage "<%= @storage.name %>"</h1>

<h2>Related halls</h2>
<table>
  <tr>
    <th>Name</th>
  </tr>
<% @storage.halls.each do |hall| %>
  <tr><td><%= link_to hall.name, hall_path(hall.id) %></td></tr>
<% end %>
</table>